name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: [1.20.x]
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: ./actions/setup-go/action.yml
      with:
        cache: true
        go-version: ${{ matrix.go_version }}
        cache-dependency-path: './go.sum'

    - name: Verify go dependency paths
      run: |
        echo "$(go env GOMODCACHE)";
        echo "$(go env GOCACHE)"

    #- name: Cache Go dependencies
    #  uses: actions/cache@v3
    #  with:
    #    key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('./go.sum') }}
    #    restore-keys: ${{ runner.os }}-go-${{ matrix.go-version }}-
    #    path: |
    #      /home/runner/go/pkg/mod
    #      /home/runner/.cache/go-build

    - name: Test
      run: go test -v ./...

    - name: Setup examples for testing
      run: ./.github/scripts/setup_examples_test.bash

    - name: Test examples
      continue-on-error: true
      working-directory: _examples
      run: go test -v -mod=mod -cover -race ./...
